var offset = 0.5;           // OFFSET BETWEEN THE 5 TRACKS OF THE ROAD


var score = 0;              // PLAYER SCORE -- IT WILL INCREMENT EVERY TIME THE PLAYER GETS A BITCOIN 

var invincible = false;     // THE CAR IS INVINCIBLE FOR 3SECS ONCE YOU TAKE THE NITRO

var max_distance = 70;      // MAX DISTANCE FROM THE CAMERA IN WHICH THE BITCOINS WILL SPAWN, 
                            // TO KEEP CLEAN AND FAST THE GAME

